"""Initial Stage 1 schema for IntelliWatch.

Revision ID: 0001_initial_core
Revises:
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial_core"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=240), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('framework', sa.String(length=80), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('factory_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('floor_plan_ref', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cameras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('stream_url_ref', sa.String(length=500), nullable=True),
    sa.Column('playback_url', sa.String(length=500), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('calibration_ref', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_health',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('dropped_frames', sa.Integer(), nullable=True),
    sa.Column('health_state', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('relation', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_objects',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('object_class', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('embedding_ref', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('polygon', sa.JSON(), nullable=False),
    sa.Column('zone_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('dwell_threshold_seconds', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behaviour_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('behaviour_type', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['tracked_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('observation_key', sa.String(length=180), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=True),
    sa.Column('model_version_id', sa.String(length=36), nullable=True),
    sa.Column('frame_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('object_class', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('mask_ref', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_id'], ['tracked_objects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_key', name='uq_detections_observation_key')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('object_ids', sa.JSON(), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('evidence_ref', sa.String(length=500), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_events_idempotency_key')
    )
    op.create_table('ppe_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('helmet', sa.Boolean(), nullable=True),
    sa.Column('vest', sa.Boolean(), nullable=True),
    sa.Column('gloves', sa.Boolean(), nullable=True),
    sa.Column('goggles', sa.Boolean(), nullable=True),
    sa.Column('confidences', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['tracked_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_points',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('depth_m', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('direction_deg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['tracked_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('before_clip', sa.String(length=500), nullable=True),
    sa.Column('event_clip', sa.String(length=500), nullable=True),
    sa.Column('after_clip', sa.String(length=500), nullable=True),
    sa.Column('snapshot', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_sites_factory_id'), 'sites', ['factory_id'], unique=False)
    op.create_index(op.f('ix_cameras_site_id'), 'cameras', ['site_id'], unique=False)
    op.create_index(op.f('ix_camera_health_camera_id'), 'camera_health', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_health_timestamp'), 'camera_health', ['timestamp'], unique=False)
    op.create_index(op.f('ix_machine_states_camera_id'), 'machine_states', ['camera_id'], unique=False)
    op.create_index(op.f('ix_machine_states_machine_id'), 'machine_states', ['machine_id'], unique=False)
    op.create_index(op.f('ix_machine_states_timestamp'), 'machine_states', ['timestamp'], unique=False)
    op.create_index(op.f('ix_scene_relationships_camera_id'), 'scene_relationships', ['camera_id'], unique=False)
    op.create_index(op.f('ix_scene_relationships_object_id'), 'scene_relationships', ['object_id'], unique=False)
    op.create_index(op.f('ix_scene_relationships_subject_id'), 'scene_relationships', ['subject_id'], unique=False)
    op.create_index(op.f('ix_scene_relationships_timestamp'), 'scene_relationships', ['timestamp'], unique=False)
    op.create_index(op.f('ix_tracked_objects_camera_id'), 'tracked_objects', ['camera_id'], unique=False)
    op.create_index(op.f('ix_zones_camera_id'), 'zones', ['camera_id'], unique=False)
    op.create_index(op.f('ix_zones_site_id'), 'zones', ['site_id'], unique=False)
    op.create_index(op.f('ix_behaviour_observations_camera_id'), 'behaviour_observations', ['camera_id'], unique=False)
    op.create_index(op.f('ix_behaviour_observations_object_id'), 'behaviour_observations', ['object_id'], unique=False)
    op.create_index(op.f('ix_behaviour_observations_timestamp'), 'behaviour_observations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_detections_camera_id'), 'detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_detections_frame_ts'), 'detections', ['frame_ts'], unique=False)
    op.create_index(op.f('ix_detections_object_id'), 'detections', ['object_id'], unique=False)
    op.create_index(op.f('ix_events_camera_id'), 'events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index('ix_events_ts_severity', 'events', ['timestamp', 'severity'], unique=False)
    op.create_index(op.f('ix_ppe_observations_object_id'), 'ppe_observations', ['object_id'], unique=False)
    op.create_index(op.f('ix_ppe_observations_timestamp'), 'ppe_observations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_track_points_object_id'), 'track_points', ['object_id'], unique=False)
    op.create_index(op.f('ix_track_points_timestamp'), 'track_points', ['timestamp'], unique=False)
    op.create_index(op.f('ix_incidents_event_id'), 'incidents', ['event_id'], unique=True)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('incidents')
    op.drop_table('track_points')
    op.drop_table('ppe_observations')
    op.drop_table('events')
    op.drop_table('detections')
    op.drop_table('behaviour_observations')
    op.drop_table('zones')
    op.drop_table('tracked_objects')
    op.drop_table('scene_relationships')
    op.drop_table('machine_states')
    op.drop_table('camera_health')
    op.drop_table('cameras')
    op.drop_table('sites')
    op.drop_table('users')
    op.drop_table('model_versions')
    op.drop_table('factories')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
